### ISSUE TITLE
Titanium Plot 2.0 on iOS throws error when building app

### ISSUE THREAD

**Issue by yozef** [Plotprojects/plot-titanium-module#7] opened 2017-12-06 17:02 UTC
The Error:
```
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Products/Debug-iphonesimulator/MyApp.app/MyApp normal x86_64
[ERROR] :  (1 failure)

```
I think the issue stems from the 64-bit requirements for iOS modules.

If I use plot version 1.15.x, it works.
When I select plot version 2.0, I get the error above.

**Comment by markvandertol** [comment] 2017-12-08 16:11
Do you also run into the issue when you try to build it for a device or only when building it for a simulator?

It should also work for simulator, so we'll look into it.

**Comment by yozef** [comment] 2017-12-08 16:22
Hi Mark,
Yes, even trying to run on device, I get this build error. Thanks for the prompt response.

**Comment by andrebsampaio** [comment] 2017-12-12 13:31
Hi yozef,
I just created a test app (with Titanium version 6.2.2GA) and integrated the version 2.0.0 of the Plot projects module straight from the plot projects download page and was not able to reproduce your problem. I ran the test app on an iPad simulator (v.11.2). Could you test with the [example project](https://github.com/Plotprojects/plot-titanium-module/tree/master/plotprojects-example) we include in the repository, just for sanity check. Could you also tell me, which titanium version you're using?

**Comment by yozef** [comment] 2017-12-13 13:56
Hi @andrebsampaio 

I tried the iOS Mobile Plot v. 2.1.0, and I got the same error. 

I tried with Ti SDKs: 6.1.2.GA up till 6.3.0.GA with Plot 1.5.15 up till 2.1.0.
1.15.5 was the only version of Plot I was able to build the App (with Ti SDK 6.1.2 up till 6.3.0), no problems with 1.15.5 version of Plot.

No Code from my end required changes. I don't think any code changes from my end is required for 2.1.0, is this true?

n.b. I am using PlotFilters from within the App.

**Comment by markvandertol** [comment] 2017-12-18 12:26
We've tested it ourselves both on a device and simulator. As it seem specific to your scenario, it's more convenient to talk with our Customer Success Manager that goes into the details for your case.

I'll close it for now, but if it turns out to be an issue on our side, then I reopen the ticket.

**Closed by markvandertol** 2017-12-18 12:26 UTC
